name: shift-watcher
on:
  schedule:
    - cron: "0 13 * * *"  # runs daily at 13:00 UTC (adjust as needed)
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml beautifulsoup4
      - name: Run shift watcher
        env:
          CONFIG_YAML: ${{ secrets.CONFIG_YAML }}   # optional: store entire YAML in secrets
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          echo "${CONFIG_YAML}" > config.yaml
          python shift_watcher.py --config config.yaml
